set(CPACK_PACKAGE_NAME "${APPLICATION_NAME}")
set(CPACK_PACKAGE_VENDOR "${ORGANIZATION_NAME}")

set(CPACK_PACKAGE_VERSION_MAJOR "${APPLICATION_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${APPLICATION_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${APPLICATION_VERSION_PATCH}")

set(CPACK_PACKAGE_VERSION "${APPLICATION_VERSION}")
set(CPACK_PACKAGE_CONTACT "sadylan@gmail.com")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Simple tool for editing channels and configuration parameters of Philips FM1000 radio.")
set(CPACK_PACKAGE_EXECUTABLES qfm1000 "qFM1000")

#set(CPACK_RESOURCE_FILE_LICENSE "LICENSE.txt")
#set(CPACK_RESOURCE_FILE_README "README.txt")
#set(CPACK_RESOURCE_FILE_WELCOME "WELCOME.txt")

if (UNIX AND NOT APPLE)
    set(CPACK_GENERATOR "DEB")

    execute_process(COMMAND dpkg --print-architecture
            OUTPUT_VARIABLE CPACK_DEBIAN_PACKAGE_ARCHITECTURE
            OUTPUT_STRIP_TRAILING_WHITESPACE)

    set(CPACK_DEBIAN_PACKAGE_SECTION "misc")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS TRUE)

    execute_process(COMMAND lsb_release --short --codename
            OUTPUT_VARIABLE LSB_DISTRO_CODENAME
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_STRIP_TRAILING_WHITESPACE)

    set(CPACK_PACKAGE_FILE_NAME "qfm1000-${CPACK_PACKAGE_VERSION}-${LSB_DISTRO_CODENAME}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")
elseif (WIN32)
    set(CPACK_GENERATOR "WIX")

    set(CPACK_WIX_UPGRADE_GUID "E6D59A10-31FD-4512-868C-4F86EF50950F")
    set(CPACK_WIX_PROPERTY_ARPHELPLINK "https://github.com/sardylan/qfm1000")
    set(CPACK_WIX_LICENSE_RTF ../doc/gpl-3.0.rtf)
    #    set(CPACK_WIX_PROPERTY_ARPSIZE "0")

    set(CPACK_PACKAGE_INSTALL_DIRECTORY "qFM1000 ${CPACK_PACKAGE_VERSION}")
    set(CPACK_PACKAGE_ICON ../icons/windows/icon-256.ico)

    set(CPACK_PACKAGE_FILE_NAME "qfm1000-${CPACK_PACKAGE_VERSION}")
elseif (APPLE)
    #    set(CPACK_GENERATOR "OSXX11")
    set(CPACK_GENERATOR "Bundle")

    set(CPACK_PACKAGE_FILE_NAME "qfm1000-${CPACK_PACKAGE_VERSION}")
endif ()

include(CPack)

cpack_add_component(qfm1000
        DISPLAY_NAME "qFM1000"
        DESCRIPTION "Simple tool for editing channels and configuration parameters of Philips FM1000 radio."
        REQUIRED)

if (WIN32 OR APPLE)
    cpack_add_component(qtlibs
            DISPLAY_NAME "Qt libs"
            DESCRIPTION "Qt libraries"
            DEPENDS qfm1000)
endif ()
