name: "Build and Test (Windows)"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: Release
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_and_test_windows:
    name: Build and Test (Windows)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
        qt_ver:
          - 5.15.2
        qt_arch:
          - win64_msvc2019_64
        include:
          - os: windows-2016
            qt_ver: 5.12.10
            qt_arch: win32_msvc2017
          - os: windows-2016
            qt_ver: 5.9.9
            qt_arch: win32_msvc2015
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Qt"
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
      - name: "Create Build Environment"
        run: cmake -E make_directory ${{runner.workspace}}\build
      - name: "Configure CMake"
        working-directory: ${{runner.workspace}}\build
        run: cmake ${{runner.workspace}}/qfm1000 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DQT5_PREFIX="D:\a\qfm1000\Qt\${{ matrix.qt_ver }}\${{ matrix.qt_arch }}"
      - name: "Build"
        working-directory: ${{runner.workspace}}\build
        run: cmake --build . --config $BUILD_TYPE
      - name: "Test"
        working-directory: ${{runner.workspace}}\build
        run: ctest -C $BUILD_TYPE
