name: "Build and Test (Linux)"
on:
  push:
    branches: 
      - 0.7
  pull_request:
    branches:
      - 0.7
env:
  BUILD_TYPE: Release
  DEBIAN_FRONTEND: noninteractive
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_and_test_linux:
    name: Build and Test (Linux)
    strategy:
      matrix:
        config:
          - os: ubuntu-22.04
            pkgs: qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
          - os: ubuntu-20.04
            pkgs: qt5-default libqt5svg5-dev libqt5serialport5-dev
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Install Qt"
        shell: bash
        run: sudo apt update && sudo apt install -y ${{ matrix.config.pkgs }}
      - name: "Create Build Environment"
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: "Configure CMake"
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake ${{runner.workspace}}/qfm1000 -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: "Build"
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --parallel
      - name: "Test"
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE --output-on-failure
      - name: "Package"
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cpack
