name: "CodeCov"
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: Debug
  DEBIAN_FRONTEND: noninteractive
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build_and_test_linux:
    name: CodeCov
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Qt"
        shell: bash
        run: sudo apt install -y qt5-default libqt5svg5-dev libqt5serialport5-dev
      - name: "Create Build Environment"
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: "Configure CMake"
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake ${{runner.workspace}}/qfm1000 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_COVERAGE=True
      - name: "Build"
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --parallel
      - name: "Test"
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE --output-on-failure
      - name: "Send reports to CodeCov"
        uses: codecov/codecov-action@v1
        with:
          files:
            ${{runner.workspace}}/build/src/eeprom/test-result-eeprom-eeprom.xml
            ${{runner.workspace}}/build/src/eeprom/test-result-eeprom-values.xml
